### PR TITLE
add an interceptor to auto logout user if the session is expired

### PR DESCRIPTION
**Pull request by torkashvand**
This is the original issue: https://github.com/workfloworchestrator/example-orchestrator-ui/issues/43

### CODE REVIEW

**Comment by torkashvand** [comment]
This is the related issue: https://github.com/workfloworchestrator/example-orchestrator-ui/issues/43

**Review by pboers1988 — CHANGES_REQUESTED** [review]
Hi @torkashvand can you run prettier on this fix? Thanks!

**Comment by Georgi2704** [comment]
Fix: https://github.com/workfloworchestrator/orchestrator-ui-library/pull/1231

**Comment by pboers1988** [comment]
Closing fixed by @Georgi2704

**Pull request closed without merging**
